import type { TaskDefinition } from '../model';

const DEFINITIONS: TaskDefinition[] = [
  {
    id: 'dev-payment-error',
    department: 'dev',
    title: '支付接口故障',
    description: '线上支付突然报错，客户已经开始在群里刷问号。',
    workload: 4,
    expertise: 5,
    urgency: 5,
    bossFit: 2,
    deadlineMinutes: 45,
    employeeSuccess: 0.85,
    bossSuccess: 0.35,
  },
  {
    id: 'dev-online-crash',
    department: 'dev',
    title: '线上服务崩溃',
    description: '服务刚刚崩了，监控大屏红得很有节日气氛。',
    workload: 5,
    expertise: 5,
    urgency: 5,
    bossFit: 3,
    deadlineMinutes: 30,
    employeeSuccess: 0.9,
    bossSuccess: 0.3,
  },
  {
    id: 'dev-capacity',
    department: 'dev',
    title: '服务器紧急扩容',
    description: '访问量暴涨，服务器正在用风扇表达意见。',
    workload: 4,
    expertise: 5,
    urgency: 4,
    bossFit: 2,
    deadlineMinutes: 60,
    employeeSuccess: 0.8,
    bossSuccess: 0.25,
  },
  {
    id: 'dev-button-color',
    department: 'dev',
    title: '修改按钮颜色',
    description: '客户原话只有六个字：按钮再红一点。',
    workload: 1,
    expertise: 2,
    urgency: 1,
    bossFit: 1,
    deadlineMinutes: 180,
    employeeSuccess: 0.95,
    bossSuccess: 0.6,
  },
  {
    id: 'product-new-feature',
    department: 'product',
    title: '客户临时加功能',
    description: '客户把“顺手加一下”说得像复制粘贴。',
    workload: 4,
    expertise: 3,
    urgency: 4,
    bossFit: 3,
    deadlineMinutes: 90,
    employeeSuccess: 0.75,
    bossSuccess: 0.5,
  },
  {
    id: 'product-scope-conflict',
    department: 'product',
    title: '需求口径打架',
    description: '三个群里出现了四个版本的最终需求。',
    workload: 3,
    expertise: 3,
    urgency: 3,
    bossFit: 4,
    deadlineMinutes: 120,
    employeeSuccess: 0.7,
    bossSuccess: 0.75,
  },
  {
    id: 'product-metric',
    department: 'product',
    title: '定义增长指标',
    description: '老板说要增长，但没人知道增长具体指什么。',
    workload: 2,
    expertise: 4,
    urgency: 2,
    bossFit: 3,
    deadlineMinutes: 150,
    employeeSuccess: 0.8,
    bossSuccess: 0.55,
  },
  {
    id: 'ops-launch-ppt',
    department: 'ops',
    title: '发布会 PPT',
    description: '发布会下午开始，PPT 还停留在新建文件。',
    workload: 3,
    expertise: 2,
    urgency: 5,
    bossFit: 2,
    deadlineMinutes: 60,
    employeeSuccess: 0.85,
    bossSuccess: 0.55,
  },
  {
    id: 'ops-official-copy',
    department: 'ops',
    title: '公众号文案',
    description: '今晚必须发文，标题已经改到第二十八版。',
    workload: 2,
    expertise: 2,
    urgency: 4,
    bossFit: 1,
    deadlineMinutes: 90,
    employeeSuccess: 0.9,
    bossSuccess: 0.45,
  },
  {
    id: 'ops-live-incident',
    department: 'ops',
    title: '直播活动事故',
    description: '直播间突然翻车，弹幕比应急方案先到。',
    workload: 4,
    expertise: 3,
    urgency: 5,
    bossFit: 4,
    deadlineMinutes: 30,
    employeeSuccess: 0.75,
    bossSuccess: 0.7,
  },
  {
    id: 'sales-complaint',
    department: 'sales',
    title: '大客户投诉',
    description: '大客户要求老板亲自解释为什么又延期了。',
    workload: 3,
    expertise: 2,
    urgency: 5,
    bossFit: 5,
    deadlineMinutes: 45,
    employeeSuccess: 0.6,
    bossSuccess: 0.9,
  },
  {
    id: 'sales-renewal',
    department: 'sales',
    title: '续约折扣谈判',
    description: '客户愿意续约，但折扣已经谈出了骨折感。',
    workload: 3,
    expertise: 3,
    urgency: 4,
    bossFit: 5,
    deadlineMinutes: 90,
    employeeSuccess: 0.65,
    bossSuccess: 0.85,
  },
  {
    id: 'sales-overpromise',
    department: 'sales',
    title: '超范围交付承诺',
    description: '老板昨晚答应的功能，研发今天第一次听说。',
    workload: 4,
    expertise: 2,
    urgency: 5,
    bossFit: 5,
    deadlineMinutes: 60,
    employeeSuccess: 0.55,
    bossSuccess: 0.8,
  },
  {
    id: 'hr-resignation',
    department: 'hr',
    title: '核心员工准备离职',
    description: '核心员工把离职信命名为“个人发展规划”。',
    workload: 3,
    expertise: 3,
    urgency: 5,
    bossFit: 5,
    deadlineMinutes: 45,
    employeeSuccess: 0.65,
    bossSuccess: 0.85,
  },
  {
    id: 'hr-hiring',
    department: 'hr',
    title: '招聘名额审批',
    description: '团队缺人，但每个审批人都建议再评估一下。',
    workload: 2,
    expertise: 2,
    urgency: 3,
    bossFit: 4,
    deadlineMinutes: 120,
    employeeSuccess: 0.8,
    bossSuccess: 0.8,
  },
  {
    id: 'hr-conflict',
    department: 'hr',
    title: '团队公开争执',
    description: '两个部门在大群里用“收到”进行激烈交流。',
    workload: 3,
    expertise: 4,
    urgency: 4,
    bossFit: 5,
    deadlineMinutes: 60,
    employeeSuccess: 0.7,
    bossSuccess: 0.8,
  },
  {
    id: 'finance-cashflow',
    department: 'finance',
    title: '现金流异常',
    description: '账上数字很安静，财务的表情不太安静。',
    workload: 5,
    expertise: 5,
    urgency: 5,
    bossFit: 5,
    deadlineMinutes: 45,
    employeeSuccess: 0.75,
    bossSuccess: 0.75,
  },
  {
    id: 'finance-invoice',
    department: 'finance',
    title: '发票抬头错误',
    description: '一张发票写错抬头，已经旅行了三个部门。',
    workload: 2,
    expertise: 3,
    urgency: 3,
    bossFit: 1,
    deadlineMinutes: 120,
    employeeSuccess: 0.9,
    bossSuccess: 0.35,
  },
  {
    id: 'finance-vendor',
    department: 'finance',
    title: '供应商催款',
    description: '供应商第六次来电，语气一次比一次像老朋友。',
    workload: 3,
    expertise: 4,
    urgency: 4,
    bossFit: 4,
    deadlineMinutes: 90,
    employeeSuccess: 0.8,
    bossSuccess: 0.7,
  },
  {
    id: 'admin-coffee',
    department: 'admin',
    title: '咖啡机坏了',
    description: '咖啡机停止工作，公司真正的核心系统宕机了。',
    workload: 1,
    expertise: 1,
    urgency: 1,
    bossFit: 1,
    deadlineMinutes: 180,
    employeeSuccess: 0.95,
    bossSuccess: 0.9,
  },
];

export const TASK_DEFINITIONS: readonly TaskDefinition[] = Object.freeze(
  DEFINITIONS.map((definition) => Object.freeze(definition)),
);
